### ISSUE TITLE
Node red UI Widget shows HTML / JSON output

### ISSUE THREAD

**Issue by mhxsol** [SergiuToporjinschi/node-red-contrib-heater-controller#19]
I use Node-RED together with Home Assistant.
After te last update of Node-RED 1.4.0 the heater widget on the UI of Node-RED shows the code.
After scrolling (a long way) down I find the widget. See screenshot below.
![image](https://user-images.githubusercontent.com/36034237/54495205-18f48e80-48e2-11e9-8f3f-02217c48d515.png)
Do you have any idea how to fix this?

Thanks in advance.
Marco

**Comment by SergiuToporjinschi** [comment]
@mhxsol node-red 1.4.0?!!? I never had that version ..... I'm using 2.0.2 now;
I can see that calendar icon is red, I think that is read because the calendar is missing. To be honest I did not test it without calendar, because I think is mandatory. Or at least should be. I think either way you should not have the code displayed.  
Nevertheless, I did not supported 1.4.0 and I don't plan to do it :) 
Can you open the developer console to see also the errors from browser?

**Comment by mhxsol** [comment]
Thanks for the quick response.
Apparently hassio is missing with version, version 1.4.0 of Node-red in hassio was version 0.20.0.
I just updates to node-red version 0.20.2 (so the same version), but error remains both in chrome and safari (on osx).
Console give several error.
![image](https://user-images.githubusercontent.com/36034237/54562169-ba551080-49c6-11e9-8e1a-46506857fbd4.png)

Hopefully you can make something out of it!

I will also try the ui_heater_controller on another (stand-alone) node-red version. Just to check if the combination with hassio isn't  the problem.

**Comment by mhxsol** [comment]
Hello Sergiu,
Today hassio released a new version of node-red (V0.20.3) and the problem is solved.
So probably a bug in de UI of node-red, but problem is fixed.
Thanks anyway for the support and your very nice node-red contribution heater-control for.
