### ISSUE TITLE
suggestion: 0.1 increment in Hysteresis

### ISSUE THREAD

**Issue by ravensergio** [SergiuToporjinschi/node-red-contrib-heater-controller#33]
I would like to set the hysteresis in .1 increments instead of 0.5. Is this possible? For Example, at set temp of 22.5 i would like it to start at 22.0 and stop at 22.8 , because 23 is already too much and it takes too long to get there. Also 22.5 is kinda short. I tried using by setting it manually the Upper to 0.3 , but is with red and as i don't know if it is working. 
Thank you for this, otherwise is working really nice, i've integrated your heater into Home assistant lovelace (in a iframe) via node-red plugin (screenshot below):
![shot](https://user-images.githubusercontent.com/32698066/72055571-bbe42200-32d3-11ea-854f-b1eaa5094805.png)

**Comment by SergiuToporjinschi** [comment]
Hi, Sorry for the late response
Just change the step in properties on that node.
![image](https://user-images.githubusercontent.com/9376439/72515149-0cb9c480-3858-11ea-94bf-bf1d6994209d.png)
![image](https://user-images.githubusercontent.com/9376439/72515153-10e5e200-3858-11ea-9672-e52167447631.png)

**Comment by ravensergio** [comment]
Hi. Thank you for replying. I think you misunderstood me.
I was talking about the HYSTERESIS steps, not the slider ones.

**Comment by SergiuToporjinschi** [comment]
@ravensergio Yes I missed HYSTERESIS word I reopened the ticket

**Comment by SergiuToporjinschi** [comment]
@ravensergio  I just looked on the code, seems that I've set the step to 0.5 in html tag but in validation needs to be  >= -100 and <= 100;
Even if appears red should work with the value that you set. please try it and let me know.
Looking on it without testing and running seems that is just an interface problem showing the field as red because the step is set to 0.5.

**Comment by ravensergio** [comment]
Alright i did that now. I've set the upper to 0.2 and I will monitor it today to see if it works. I will get back after that.
Thank you.

**Comment by SergiuToporjinschi** [comment]
@ravensergio  just a quick question ... I noticed that the title of your card is in romanian language. I've missed something or you are romanian?

**Comment by ravensergio** [comment]
@SergiuToporjinschi Yes I am romanian. Also I've tested with 0.1 increment, regardless of the "red" warning in html, and it seems that is working. Thank you for your help and for this awesome node.
 If you noticed the https://github.com/SergiuToporjinschi/node-red-contrib-heater-controller/issues/25 issue, i've commented there how i changed the heater to act as a mqtt HVAC for Home Assistant, in order to have a more "native" card for lovelace (no iframe cause iframe resizing is strange on different screens).

**Comment by SergiuToporjinschi** [comment]
Looking now on this screen shut and I like your colors. What I don't like is that colors from my node is not matching  those, Can you tel me how did you set the that orange color? because I noticed that Dashboard is giving me some theme colors but I don't know which is that. I can use those values and then you will have a matching design.
