### ISSUE TITLE
RESET bar and SIZE 

### ISSUE THREAD

**Issue by bburkett52** [SergiuToporjinschi/node-red-contrib-heater-controller#34]
First of all, great job with this node! Very much appreciated!

I am using this node to control heat in my garage and it works well. The issue I have is that, on my iPhone, I am unable to "click" on display to reset a manual setting. I saw on another issue, posted here, that an image that showed a RESET bar on the node. I am using version 1.2.2, which I believe is current, and I do not have that RESET bar. I assume this RESET bar would do the temperature reset?

Also, I saw on that same post that you had the size of the node display set to 8x4. I am unable to set the size larger than 6x4.

Can you advise on these questions?

Regards,
Bob

![Screenshot from 2020-01-16 08-43-01](https://user-images.githubusercontent.com/35471928/72531176-ed626d80-383e-11ea-8685-c440c753d133.png)

**Comment by SergiuToporjinschi** [comment]
Hi, 
Is no reset bar. the reset can be done by double click, double tap the target temperature (big number) or by slide that big number to the right or left. Now the problem is, that is not working on IPhone. (un)Fortunately I'm not  a Mac user so I don't have any device to see what's happening. 
When I will get one I will see, maybe I can fix that. I did not test it with the latest version I'm currently using 1.0.2

**Comment by bburkett52** [comment]
Thanks for quick reply! I’m sure it’s a tough job to test with ALL possible devices! 

Thanks again for all your work!

~Bob
