### ISSUE TITLE
moving the slider triggers a swipe

### ISSUE THREAD

**Issue by bgewehr** [SergiuToporjinschi/node-red-contrib-heater-controller#37]
The slider for the target-temp does not stop the horizontal mouse movement events from propagating so the dashboard page changes when swipe pages is "on".

![image](https://user-images.githubusercontent.com/4056277/73395166-399dbb00-42df-11ea-8720-2e4f9eb7cc2e.png)

Could you add 

`event.stopPropagation();` probably?

**Comment by SergiuToporjinschi** [comment]
Hi @bgewehr ,
Thank you for letting me know about this. But unfortunately, angular is not calling my function with the event; 
So is not quite possible. This is quite ugly, but I have a good news. 
In next release I've added an option to have buttons and not a slider, should resolve this. Plus that in safarii resetting the custom value is not possible, and new new interface will allow you to push a button to reset it.

**Comment by SergiuToporjinschi** [comment]
Here is a preview ;) 
![image](https://user-images.githubusercontent.com/9376439/73453518-dbbbb280-4374-11ea-8c8f-f6f57c93e099.png)

**Comment by bgewehr** [comment]
Cool! Personally I‘d prefer the details on the right but that’s just a personal taste.

Will you allow to edit the calendar via the widget? (It would be powerful to do that seperated and so to offer a generic weekdayplanner for all devices by just adding one to a group...

**Comment by SergiuToporjinschi** [comment]
@bgewehr  I would like to, but unfortunately I'm quite restricted by dashboard ui;
I have other enhancement plan which I cannot finish due to this restriction; I wanted to have a button to open a dialog and display the logs (when the signal was send out from my node) and unfortunately I cannot open the dialog.  Because in angular I need to have control of how the controller is define, but in Dashboard I don't have the standard angular definition so I cannot access the module.

**Comment by bgewehr** [comment]
What about a lightbox like https://noelboss.github.io/featherlight/

**Comment by SergiuToporjinschi** [comment]
@bgewehr hmmm I did worked with that but it could be useful. Thanks for the tip, I will take this in consideration
